### ISSUE TITLE
Removal of construct_url/2, construct_url/3

### ISSUE THREAD

**Issue by keithhamilton** [kivra/restclient#6]
Hi!

Just curious what the rationale was for removing these convenience methods during the big refactor? Is there a plan to re-add them at some point or are they permanently gone?

One way or the other the current README.md is incorrect in listing `construct_url` as a convenience method.

**Comment by plux** [comment]
Hi!

Thanks for letting us know about this issue!

I see no reason to remove it, so I will add it back in again.

**Comment by keithhamilton** [comment]
Awesome!

**Comment by plux** [comment]
0.3.0 is released now, with construct_url added back in.
